# site settings
title: Apoorva Joshi
subtitle: Data Scientist
email: appujo@gmail.com
description: 
baseurl: ""
url: https://ajosh0504.github.io
city: San Jose
state: CA 
zip_code: 
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
github_url: https://github.com/ajosh0504/
linkedin_url: https://www.linkedin.com/in/apoorvajoshi95/

# build settings
markdown: kramdown

sass:
  style: compressed